################### SERVER ##########################
spring.application.name=ProyectoDP_Final
server.port=8090

spring.datasource.url=jdbc:h2:mem:proyectodp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#http://localhost:8090/h2-console

################### JPA ##########################
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#para cargar data inicial data.sql
spring.jpa.defer-datasource-initialization=true

# SWAGGER
#http://localhost:8090/swagger-ui/index.html